export interface TextTransformation {
  readonly priority: number;
  readonly type: TextTransformationType;
}

export enum TextTransformationType {
  NONE = 'NONE',
  COMPRESS_WHITE_SPACE = 'COMPRESS_WHITE_SPACE',
  HTML_ENTITY_DECODE = 'HTML_ENTITY_DECODE',
  LOWERCASE = 'LOWERCASE',
  CMD_LINE = 'CMD_LINE',
  URL_DECODE = 'URL_DECODE',
  BASE64_DECODE = 'BASE64_DECODE',
  HEX_DECODE = 'HEX_DECODE',
  MD5 = 'MD5',
  REPLACE_COMMENTS = 'REPLACE_COMMENTS',
  ESCAPE_SEQ_DECODE = 'ESCAPE_SEQ_DECODE',
  SQL_HEX_DECODE = 'SQL_HEX_DECODE',
  CSS_DECODE = 'CSS_DECODE',
  JS_DECODE = 'JS_DECODE',
  NORMALIZE_PATH = 'NORMALIZE_PATH',
  NORMALIZE_PATH_WIN = 'NORMALIZE_PATH_WIN',
  REMOVE_NULLS = 'REMOVE_NULLS',
  REPLACE_NULLS = 'REPLACE_NULLS',
  BASE64_DECODE_EXT = 'BASE64_DECODE_EXT',
  URL_DECODE_UNI = 'URL_DECODE_UNI',
  UTF8_TO_UNICODE = 'UTF8_TO_UNICODE',
}